[package]
name = "jaeymo/profiler"
description = "Manages and transitions between profiles"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2.0.0"
GeneralUtil = "jaeymo/general-util@0.3.1"