[package]
name = "jaeymo/viewer"
description = "Observor methods for instances"
license = "MIT"
authors = ["Jaeymo <jaey.cyber@gmail.com>"]
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"