[package]
name = "jaeymo/general-util"
description = "Simple utility functions"
license = "MIT"
authors = ["jaeymo"]
version = "0.3.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"