[package]
name = "jaeymo/better-animation"
description = "Simplifies client-side animation management"
version = "1.0.0"
license = "MIT"
authors = ["jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"